### ISSUE TITLE
您好，请问可以提供训练代码参考一下吗？

### ISSUE THREAD

**Issue by porcofly** [hlzz/mirror#2]
您好，请问可否提供训练代码？

**Comment by hlzz** [comment]
@porcofly , please see train.py for an example. It may not be workable with this open-source version, but it can be used as a reference for your implementation.

**Comment by porcofly** [comment]
> @porcofly , please see train.py for an example. It may not be workable with this open-source version, but it can be used as a reference for your implementation.
