### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by porcofly** [hlzz/mirror#3]
`
def main(argv=None):  

    image_list_path = os.path.join(FLAGS.gl3d, 'list', 'global_stats', 'global_img_list.txt')
    train_list_path = os.path.join(FLAGS.gl3d, 'forward', 'train_list_with_mask.bin')

    image_list = read_list(image_list_path)
    train_list = read_samples(train_list_path)
    train(train_list, image_list, FLAGS.net)
`
Can you tell me what these two files `global_img_list.txt` and `train_list_with_mask.bin` are? What do I need to do with GL3D data?
which txt file is the global_img_list.txt？
![屏幕快照 2019-05-28 下午10 16 44](https://user-images.githubusercontent.com/29138847/58485313-5e60f200-8196-11e9-901a-da1290473994.png)

**Comment by hlzz** [comment]
See the updated README
